### ISSUE TITLE
rimworld 1.3 bug

### ISSUE THREAD

**Issue by papatalok** [kwang4/Originals-RimworldMod#4]
rimworld spams ressurection when pawn head is decapitated

**Comment by kwang4** [comment]
Just checked with debug mode options, decapitating an Original doesn't spam messages, it just resurrects. This was an old bug I fixed a while ago, make sure you've updated from either the releases or zip file or Rimworld Base. (If the issue persists, please send me a save file with the issue so I can test it.)

**Comment by papatalok** [comment]
Its already fixed. I just reorganized my mod order.
