### ISSUE TITLE
Sickness

### ISSUE THREAD

**Issue by tederman** [kwang4/Originals-RimworldMod#6]
hi!
my pawn got infected with **muscle parasites** and I couldn't treat him as he was constantly getting 200% tend quality but the required 0/300% tend quality stayed at 0. think it's the Originals mod's doing but **i'm not sure** so just letting u know.

guess I could have killed the pawn and waited for the resurrection but chose to savescum instead :p
thank you for the mod btw!

**Comment by kwang4** [comment]
Hey there! Thanks for catching this bug, I believe I've just fixed it with the new release. Please replace your current mod files with the updated ones in releases/Rimworld Base site. I'm closing the issue, but feel free to reopen it if something turns out to still be buggy.
